<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="Confluent.Kafka" />
      <PackageReference Include="FluentEmail.Core" />
      <PackageReference Include="FluentEmail.MailKit" />
      <PackageReference Include="FluentEmail.Smtp" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="EmailSending\Templates\VerifyEmail\en.html" />
      <EmbeddedResource Include="EmailSending\Templates\**\*.html" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Common\SharedKernel\SharedKernel.csproj" />
    </ItemGroup>

</Project>
