<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\Modules.Users.Domain\Modules.Users.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" />
      <PackageReference Include="MediatR.Contracts" />
    </ItemGroup>

</Project>
