<Project Sdk="Microsoft.NET.Sdk">
  
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MediatR.Contracts" />
      <PackageReference Include="Newtonsoft.Json" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Confluent.Kafka">
        <HintPath>..\..\..\..\..\.nuget\packages\confluent.kafka\2.13.0\lib\net8.0\Confluent.Kafka.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
