<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\Modules.Users.Application\Modules.Users.Application.csproj" />
      <ProjectReference Include="..\Modules.Users.Endpoints\Modules.Users.Endpoints.csproj" />
      <ProjectReference Include="..\Modules.Users.Persistence\Modules.Users.Persistence.csproj" />
      <ProjectReference Include="..\SharedKernel\SharedKernel.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
      <PackageReference Include="Konscious.Security.Cryptography.Argon2" />
      <PackageReference Include="MediatR" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
      <PackageReference Include="EFCore.NamingConventions" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

</Project>
